import "reflect-metadata"

process.env.NODE_ENV = "test"
process.env.APP_NAME = "API"
process.env.APP_VERSION = "1.0.0"
process.env.APP_TIMEZONE = "UTC"
process.env.API_DOCS_ENABLED = "false"
process.env.API_DEBUG_ERRORS = "false"
process.env.LOG_LEVEL = "silent"
process.env.DATABASE_URL = "postgres://api:api@localhost:5432/api_test"
process.env.ALLOWED_ORIGINS = "http://localhost:3000"
process.env.ALLOWED_METHODS = "GET,POST"
process.env.ALLOWED_HEADERS = "Content-Type,Authorization"
process.env.MAX_AGE = "3600"
process.env.CREDENTIALS = "false"
